language: objective-c
osx_image: xcode9
xcode_project: CariocaMenu.xcodeproj
destination: 'platform=iOS Simulator,name=iPhone 7,OS=9'
sdk: iphonesimulator ONLY_ACTIVE_ARCH=NO
# before_install:
# - brew update
# - brew install xctool
script:
  - xcodebuild -target CariocaMenu-iOS
  - xcodebuild -target CariocaMenuDemo
  # - xctool -project CariocaMenu.xcodeproj -scheme CariocaMenuTests
# after_success:
